name: Deploy Prod

on:
  # TODO: deploy automatically when we are confident in this.
  # push:
  #   tags: ["v*"]
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to deploy"
        required: true
        default: "main"
      oci-tag:
        description: "OCI image tag to publish"
        required: true
        default: "latest"

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - id: setup-gcloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/216981959795/locations/global/workloadIdentityPools/github-idpool/providers/github-provider"
          service_account: "github-ci@gittuf-451517.iam.gserviceaccount.com"
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - uses: ko-build/setup-ko@v0.8
        env:
          KO_DOCKER_REPO: us-docker.pkg.dev/gittuf-451517/gittuf

      - name: Build image
        env:
          KO_DEFAULTBASEIMAGE: "cgr.dev/chainguard/git:latest"
        run: |
          digest=$(ko build .)
          echo "IMAGE_DIGEST=$digest" >> "$GITHUB_ENV"

      - name: Deploy image
        run: |
          gcloud run deploy app \
            --image "${IMAGE_DIGEST}" \
            --region us-central1 \
            --allow-unauthenticated \
            --service-account gittuf-app@gittuf-451517.iam.gserviceaccount.com \
            --project gittuf-451517 \
            --update-env-vars=APP_EMAIL_ID="179610826+gittuf-app-test[bot]@users.noreply.github.com",KMS_KEY="projects/gittuf-451517/locations/global/keyRings/gittuf-github-app/cryptoKeys/gittuf-github-webhook-key/cryptoKeyVersions/7",GET_USER_SIGNATURE="false",GITHUB_APP_ID="980634",CLOUD_PROVIDER="gcp",GITHUB_WEBHOOK_SECRET="projects/216981959795/secrets/github-webhook-secret/versions/1",APP_SIGNING_KEY="projects/216981959795/secrets/gittuf-app-signing-key/versions/1",APP_SIGNING_PUBKEY="projects/216981959795/secrets/gittuf-app-signing-pubkey/versions/1",GITTUF_DEV="1"
