name: golangci-lint
on:
  push:
    branches: ['main']
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
permissions: read-all
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: '1.24'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd
        with:
          version: latest
