name: golangci-lint
on:
  push:
    branches: ['main']
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
permissions: read-all
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version: '1.23'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@e0ebdd245eea59746bb0b28ea6a9871d3e35fbc9
        with:
          version: latest
